# Generated by Django 5.2.7 on 2025-10-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPIOConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this GPIO connection pair (e.g., 'Jetson-1', 'Device-A')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "reset",
                    models.IntegerField(
                        help_text="BCM GPIO pin number for reset control"
                    ),
                ),
                (
                    "force_recovery",
                    models.IntegerField(
                        help_text="BCM GPIO pin number for force recovery control"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this connection controls or where it goes",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connection is enabled and available for control",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GPIO Connection",
                "verbose_name_plural": "GPIO Connections",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reset", "force_recovery"), name="unique_pin_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JetsonNanoDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Jetson Nano device",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this device or its location",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device is currently active/accessible",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GPIO connection this device is currently connected to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gpio_controller.gpioconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jetson Nano Device",
                "verbose_name_plural": "Jetson Nano Devices",
                "ordering": ["name"],
            },
        ),
    ]
