# Generated by Django 5.2.7 on 2025-10-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpio_controller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jetsonnanodevice",
            name="usb_connection",
            field=models.CharField(
                blank=True,
                help_text="Optional USB connection identifier (path, serial or port)",
                max_length=200,
            ),
        ),
    ]
